### ISSUE TITLE
previous work issues

### ISSUE THREAD

**Issue by testbird** [cythoning/pyznap#3]
Skimming through the issues of zfs-auto-snapshot, sanoid and znapzend I met some thoughts that made me think whether pyznap has them covered. For example, temporarily disconnected operation, and there seems to be a limit in number of snaps that zfs can delete at once.

Maybe it holds some insights, if you get the chance to skim through their issues.

**Comment by cythoning** [comment]
I did skim through some of those issues, and I built pyznap with some of those in mind already, like atomic snapshots, frequent (15min) & weekly snapshots, etc. But I cannot go through all of them and try to reproduce those. If you have specific issues or improvements you can open an issue here and I will try to work on that.

**Comment by testbird** [comment]
Most interesting to know for me now would be support to resume interrupted transfers (token fetching and parameter).
https://github.com/cythoning/pyznap/issues/3#issuecomment-353942170

And maybe the backup server fetching snaps from clients.

**Comment by testbird** [comment]
Oops, that's https://github.com/oetiker/znapzend/issues/298

**Comment by cythoning** [comment]
As far as I know, resumable receive is only supported in zfsonlinux 0.7.x, while all major distributions only ship with 0.6.x. So I cannot really implement it until Ubuntu's zfsonlinux supports it.

pyznap's send/recv is incremental though, so any snapshot that was fully received on the destination will not have to be sent again, even if transfer is interrupted. The initial replication might take long if the oldest snapshot is quite big, but incremental updates shouldn't be too big and if you take frequent snapshots, then there shouldn't be a problem with interruption. 


As for fetching snaps: For that I would have to implement sending from a ssh location. I'll have to think about this.

**Comment by testbird** [comment]
Hm, thanks wasn't aware of the release state, then encryption would also need a compiled module.
(which needs "raw send" https://github.com/jimsalterjrs/sanoid/issues/150)

Looks like a zfs version check in pyznap will be required anyway to support resume (and encryption), because the package management system can't check remote server dependencies.

**Comment by testbird** [comment]
Oh, and one more thing considering off-site backup would be compression.
https://github.com/jimsalterjrs/sanoid/issues/123

**Comment by cythoning** [comment]
I've been thinking about this, will add this soon hopefully.

**Comment by testbird** [comment]
Debian has 0.7.3 in backports :-)

**Comment by testbird** [comment]
Meaning encryption and compression would need a "raw" send/receive command available on the remote site.

**Comment by cythoning** [comment]
I'm on Ubuntu 16.04 and zfsonlinux 6.5.6, which does not have encryption :). 'raw' send/recv will only be necessary once encryption is available, but I will be very interested in that once it makes its way into Ubuntu LTS. Implementing it would be quite easy I think, just one more flag '-w', which would be trivial.

**Comment by cythoning** [comment]
I'll close this for now. send/resume I can only implement once zfsonlinux 0.7.0 is released on Ubuntu. snapshot fetching I might be able to do, but might be a bit tricky, I'll have to think about that.
Thanks for the suggestions. If you have any other specific issues please let me know.
