### ISSUE TITLE
Pre and Post sync/send commands

### ISSUE THREAD

**Issue by redmop** [cythoning/pyznap#4]
I'd like to run things just before and after snapshots (stop a database, pause a VM, or rsync something), and just before and after sending (ssh into the destination, lock/unlock luks encrypted partitions, and import/export a zfs pool).

The scripts that do the jobs are easy enough. Can there be a hook to call those scripts?

**Comment by cythoning** [comment]
I had the same issue: I have to import a zpool, then run pyznap and export it again. The way I did it is just run these commands in the cronjob before running pyznap, e.g. my nightly backup cronjob looks like this:

    0 0 * * *       root    { /sbin/zpool import tank ; /opt/pyznap/src/pyznap.py send ; /opt/pyznap/src/pyznap.py snap --clean ; sleep 10 ; /sbin/zpool export tank ; }  >> /var/log/pyznap.log

I don't really want to modify pyznap such that it calls scrips before and after execution, I think having a short bash script with all things to be done before and after pyznap and calling this in the cronjob is the best solution.

**Comment by redmop** [comment]
There is good reason to integrate. Say you have 3 datasets with different backup schedules. One includes a database that needs stopping before the snapshot, but it only needs run daily. The rest run every 15 min. To minimize downtime, I'd want to run it only for snapshotting the dataset with the database.  If you put the database stoppage in the same cron job as the pyznap run, the DB is stopped every 15 min. If you make the DB stop have it's own cron job, it will need to be down longer AND wait until the pyznap run is complete. This is harder to check for.

**Comment by cythoning** [comment]
Hm yes, I see your reasoning. I'll have a look at it, but don't expect anything soon.

In the meantime you could have two config files for the different schedules and use pyznap with the `--config` flag. For the DB you then have one daily cronjob stopping the DB, taking snapshot and restarting again. For the rest you have your 15min cronjob/snapshots, which do not affect the DB dataset. Maybe not ideal, but should work without problem.

**Comment by cythoning** [comment]
Atomic recursive snapshots is why I moved from sanoid to pyznap :).

I'll close this for now, but I'll think about pre/post script hooks. Thanks.
